name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        java-version: ['8', '11', '17', '21', '25']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java-version }}
    - name: Build
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Test
      run: ant test
